In [1]:
import pandas as pd
df = pd.read_csv("customer_shopping_behavior.csv")

In [2]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,purchase amount(INR),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,4505,Karnataka,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,PhonePe,Fortnightly
1,2,19,Male,Sweater,Clothing,5440,Andhra Pradesh,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,6205,Telangana,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,7650,Karnataka,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,Google Pay,Weekly
4,5,45,Male,Blouse,Clothing,4165,Tamil Nadu,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,Google Pay,Annually

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   purchase amount(INR)    3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [4]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,purchase amount(INR),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,44,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Kerala,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,Google Pay,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,229,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,5079.970513,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,2013.258341,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,1700.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,3315.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,5100.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,6885.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,8500.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [5]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
purchase amount(INR)       0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [6]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [7]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
purchase amount(INR)      0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [8]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')
df = df.rename(columns={'purchase_amount(inr)': 'purchase_amount'})

In [9]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [10]:
# create a column age_group
labels = ['Young-adults', 'Adults','Middle-aged', 'Seniors']
df['age_group'] = pd.qcut(df['age'], q=4, labels = labels)

In [11]:
df[['age', 'age_group']].head(10)

   age     age_group
0   55   Middle-aged
1   19  Young-adults
2   50   Middle-aged
3   21  Young-adults
4   45   Middle-aged
5   46   Middle-aged
6   63       Seniors
7   27  Young-adults
8   26  Young-adults
9   57   Middle-aged

In [12]:
#create column purchase frequency days
frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [13]:
df[['purchase_frequency_days', 'frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually
5                        7                 Weekly
6                       90              Quarterly
7                        7                 Weekly
8                      365               Annually
9                       90              Quarterly

In [14]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [15]:
(df['discount_applied'] == df['promo_code_used']).all()

True

In [16]:
df = df.drop('promo_code_used', axis=1)

In [17]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [18]:
df.to_csv("customer_behavior_cleaned_aftershoppinganalysis.csv", index=False)

### connecting to mysql workbench

In [19]:
!pip install pymysql sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pymysql in c:\users\rsind\appdata\roaming\python\python311\site-packages (1.2.0)
Requirement already satisfied: sqlalchemy in c:\users\rsind\appdata\roaming\python\python311\site-packages (2.0.50)
Requirement already satisfied: greenlet>=1 in c:\users\rsind\appdata\roaming\python\python311\site-packages (from sqlalchemy) (3.5.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\rsind\appdata\roaming\python\python311\site-packages (from sqlalchemy) (4.15.0)

[notice] A new release of pip is available: 24.0 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [20]:
# Install required libraries
from sqlalchemy import create_engine
from urllib.parse import quote_plus

# SQL Server connection
username = "root"
password = quote_plus("sindhu@1234")

host = "localhost"
port = "3306"
database = "shopping_behaviour"

engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}"
)

connection = engine.connect()

print("Connected successfully!")

Connected successfully!

In [21]:
import pandas as pd

df = pd.read_csv("customer_behavior_cleaned_aftershoppinganalysis.csv")

print(df.head())
print(df.shape)

   customer_id  age gender item_purchased  category  purchase_amount  \
0            1   55   Male         Blouse  Clothing             4505
1            2   19   Male        Sweater  Clothing             5440
2            3   50   Male          Jeans  Clothing             6205
3            4   21   Male        Sandals  Footwear             7650
4            5   45   Male         Blouse  Clothing             4165

         location size      color  season  review_rating subscription_status  \
0       Karnataka    L       Gray  Winter            3.1                 Yes
1  Andhra Pradesh    L     Maroon  Winter            3.1                 Yes
2       Telangana    S     Maroon  Spring            3.1                 Yes
3       Karnataka    M     Maroon  Spring            3.5                 Yes
4      Tamil Nadu    M  Turquoise  Spring            2.7                 Yes

   shipping_type discount_applied  previous_purchases payment_method  \
0        Express              Yes                  14        PhonePe
1        Express              Yes                   2           Cash
2  Free Shipping              Yes                  23    Credit Card
3   Next Day Air              Yes                  49     Google Pay
4  Free Shipping              Yes                  31     Google Pay

  frequency_of_purchases     age_group  purchase_frequency_days
0            Fortnightly   Middle-aged                       14
1            Fortnightly  Young-adults                       14
2                 Weekly   Middle-aged                        7
3                 Weekly  Young-adults                        7
4               Annually   Middle-aged                      365
(3900, 19)

In [22]:
df.to_sql(
    name="customer",
    con=engine,
    if_exists="replace",
    index=False
)

print("Data loaded successfully!")

Data loaded successfully!